# Generated by Django 2.2.5 on 2021-02-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arts',
            name='output',
            field=models.ImageField(default='output/output.jpg', upload_to=''),
        ),
    ]
