# Generated by Django 2.2.5 on 2021-02-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0002_arts_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arts',
            name='output',
        ),
        migrations.AddField(
            model_name='arts',
            name='action',
            field=models.CharField(choices=[('NO_FILTER', 'no filter'), ('COLORIZED', 'colorized'), ('GRAYSCALE', 'grayscale'), ('BLURRED', 'blurred'), ('BINARY', 'binary'), ('INVERT', 'invert')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
