# Generated by Django 2.2.5 on 2021-02-21 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0003_auto_20210221_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='arts',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
