# Generated by Django 3.1.7 on 2021-03-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0004_arts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts',
            name='action',
            field=models.CharField(choices=[('UDNIE', 'Udnie'), ('CANDY', 'Candy'), ('MOSAIC', 'Mosaic'), ('PINK', 'Pink'), ('SCREAM', 'Scream'), ('LA_MUSE', 'La Muse'), ('FIRE', 'Fire'), ('FLAME', 'Flame'), ('RAIN', 'Rain'), ('LANDSCAPE', 'Landscape'), ('GOLD_BLACK', 'Gold Black'), ('TRIANGLE', 'Triangle'), ('STARRY_NIGHT', 'Starry Night'), ('WAVE', 'Wave'), ('FEATHERS', 'Feathers')], max_length=50),
        ),
    ]
